In [12]:
import numpy as np
import time
import random

# Definicion de funciones

In [19]:
def pintar_camino(tablero, array_solucion):
    # en esta funcion pintaremos el recorrido que ha tenido el árbol, despueés de encvontrar la solucion optima.
    count = 0
    for i in array_solucion:
        #contamos en qué posición se encuentra y sumamos una para luego pintar el recorrido
        count += 1
        tablero[i[0]][i[1]] = count

    return tablero

In [20]:
# Funcion para comprobar si los hijos generados son válidos
def comprobar_posicion_profundidad(tablero,ficha_posicion_p):
    # Creamos una lista vacia que almacenará los hijos creados
    array_hijos = []
    # Creamos una variable contador para poder
    aux_count=0
    # Recorremos los posibles caminos a seguir
    for new_position in [(-1, -2), (1, -2), (-2, -1), (2, -1), (-2, 1), (-1, 2), (1, 2), (2, 1)]:
        # Si está fuera del tablero no lo hara
        if (ficha_posicion_p[0] + new_position[0]) < 0 or (ficha_posicion_p[1] + new_position[1]) < 0 or (ficha_posicion_p[0] + new_position[0]) >= (len(tablero)) or (ficha_posicion_p[1] + new_position[1]) >= (len(tablero[0])):
            continue

        # Comprueba que esa posicion no haya sido visitada con anterioridad
        if tablero[(ficha_posicion_p[0] + new_position[0])][(ficha_posicion_p[1] + new_position[1])] != 0:
            continue
        aux_count+=1
        # Incluimos los hijos en la lista
        array_hijos.insert(0,[tuple((ficha_posicion_p[0] + new_position[0],ficha_posicion_p[1] + new_position[1])),ficha_posicion_p])

    # devolvemos la nueva lista con los hijos creados
    return array_hijos
    

# Esta sera la funcion recursiva que hara la busqueda
def seleccion_profundidad(tablero,ficha_posicion,array_posible):
    
    # Inicializamos la lista
    array_posible_lista = []

    # Llamamos a la funcion que genera los hijos
    array_posible_lista = comprobar_posicion_profundidad(tablero,ficha_posicion)[0:] 
    # añadimos a la lista que contendra la solucion la posicion actual 
    array_solucion.append(ficha_posicion)
    # Marcamos como ya visitada esa posicion del tablero
    tablero[array_solucion[len(array_solucion)-1][0]][array_solucion[len(array_solucion)-1][1]]=1
    
    # Comprobamos si ya hemos llegado a la solucion contando el numero de valores distintos de 0
    if (np.count_nonzero(tablero)==size_tablero**2):
        # Si no hay ningun 0, hemos visitado todo el tablero y por tanto contamos con una solucion
        lista_soluciones.append(array_solucion)
        # Devolvemos 1 y salimos recursivamente de la funcion
        return 1
    aux_count = 0
    # En caso de no haber llegado a la solucion, continuamos
    # Recorremos la lista de hijos generados
    for i in array_posible_lista:
        aux_count += 1    
        # si el padre del nodo en esa iteracion es la ficha actual
        if i[1]==ficha_posicion:
            # LLamamos recursivamente a la funcion con el hijo
            resultado=seleccion_profundidad(tablero,i[0],array_posible_lista)
            # Comprobamos que el return no haya terminado la funcion
            if resultado!=0:
                return resultado
    
    # Si sale del for, significa que ha dejado de llamar recursivamente a la funcion y esa posicion no tiene hijos, siendo un callejon sin salida
    # Eliminamos la marca en el tablero
    tablero[array_solucion[len(array_solucion)-1][0]][array_solucion[len(array_solucion)-1][1]]=0
    # Eliminamos el nodo de la lista de solucion
    array_solucion.pop()
    return 0

    

# Declaracion de variables e inicio del juego

In [29]:
#definición de variables
intro=0
size_tablero= 0
# Pedimos por pantalla la posicion del tablero
while intro == 0:
    print("Elija el tamaño del tablero:")
    size_tablero=input()
    # Control de errores
    if size_tablero.isnumeric():
        intro=1
        size_tablero= int(size_tablero)
    else:
        print("Valor no válido")

# Iniciamos la matriz de tablero a 0
tablero = np.zeros((size_tablero, size_tablero))

Elija el tamaño del tablero:


In [30]:
# Inicializamos variables
#ficha_posicion_r=(random.randint(0,3),random.randint(0,3))
ficha_posicion_r=(0,0)
num_paso=1
tablero[ficha_posicion_r[0]][ficha_posicion_r[1]]=num_paso
lista_soluciones = []
print(tablero)
juego=0
array_posible_real=[]
array_solucion=[]
array_posible_real.insert(0,[ficha_posicion_r,(-1,-1)])

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
# Aqui comienza la busqueda
inicio = time.time()
seleccion_profundidad(tablero,ficha_posicion_r,array_posible_real)
fin = time.time()
# Aqui termina

In [28]:
print("Juego terminado")
if len(lista_soluciones) == 0:
    print("No tiene solucion")
else:
    for i in lista_soluciones:
        pintar_camino(tablero, i)
        print(i)
        print("Tiempo:",fin-inicio)

        print("Tablero:\n",tablero)


Juego terminado
[(0, 0), (2, 1), (4, 2), (6, 3), (5, 5), (3, 6), (1, 5), (3, 4), (4, 6), (6, 5), (4, 4), (5, 6), (3, 5), (1, 6), (2, 4), (4, 5), (6, 6), (5, 4), (3, 3), (2, 5), (0, 6), (1, 4), (2, 6), (0, 5), (1, 3), (3, 2), (5, 3), (6, 1), (4, 0), (5, 2), (6, 4), (4, 3), (5, 1), (3, 0), (1, 1), (0, 3), (2, 2), (0, 1), (2, 0), (1, 2), (0, 4), (2, 3), (0, 2), (1, 0), (3, 1), (5, 0), (6, 2), (4, 1), (6, 0)]
Tiempo: 0.013998746871948242
Tablero:
 [[ 1. 38. 43. 36. 41. 24. 21.]
 [44. 35. 40. 25. 22.  7. 14.]
 [39.  2. 37. 42. 15. 20. 23.]
 [34. 45. 26. 19.  8. 13.  6.]
 [29. 48.  3. 32. 11. 16.  9.]
 [46. 33. 30. 27. 18.  5. 12.]
 [49. 28. 47.  4. 31. 10. 17.]]
