In [1]:
import numpy as np
import time
import random

# Definicion de funciones

In [8]:
def pintar_camino(tablero, array_solucion):
    # en esta funcion pintaremos el recorrido que ha tenido el árbol, despueés de encvontrar la solucion optima.
    count = 0
    for i in array_solucion:
        #contamos en qué posición se encuentra y sumamos una para luego pintar el recorrido
        count += 1
        tablero[i[0]][i[1]] = count

    return tablero

In [9]:
def comprobar_posicion_anchura(tablero,ficha_posicion_p):
    #en esta funcion veremos cuales son los movimientos posibles de la ficha y los guardaremos junto al padre del que venían
    array_hijos = []
    aux_count=0
    # recorremos los posibles movimientos del caballo
    for new_position in [(-1, -2), (1, -2), (-2, -1), (2, -1), (-2, 1), (-1, 2), (1, 2), (2, 1)]:
        # si la posicion a la que se intenta mover es menor que 0 o se sale de los limites del tablero, pasamos a la siguiente iteracion del for
        if (ficha_posicion_p[0] + new_position[0]) < 0 or (ficha_posicion_p[1] + new_position[1]) < 0 or (ficha_posicion_p[0] + new_position[0]) >= (len(tablero)) or (ficha_posicion_p[1] + new_position[1]) >= (len(tablero[0])):
            continue
        # si la posicion a la que se mueve del tablero es distinto de 0 entonces no puede moverse ahi porque ya habia pasado por la ficha y se salta a la siguiente iteracion
        if tablero[(ficha_posicion_p[0] + new_position[0])][(ficha_posicion_p[1] + new_position[1])] != 0:
            continue
        aux_count+=1
        # si la poscion es válida, añadimos a un array, tanto el sitio donde te vas a mover, como de donde viene.
        array_hijos.append([tuple((ficha_posicion_p[0] + new_position[0],ficha_posicion_p[1] + new_position[1])),ficha_posicion_p])

    return array_hijos
    

def seleccion_anchura(tablero,ficha_posicion,array_posible):
    
    array_posible_lista = []
    array_posible_hijos = []
    # guardamos en una variable auxiliar, los posibles hijos que tenemos respecto a la ficha posicion
    array_posible_hijos = comprobar_posicion_anchura(tablero,ficha_posicion)[0:] 
    #como hacemos una busqueda en profundidad, hay que comprobar que los hijos no sean solucion y abrir todos sus nodos
    #recorremos los posibles hijos
    for i in array_posible_hijos:
        #añadimos a la lista posible de nodos todos los nodos que se abran de los posibles hijos
        array_posible_lista = array_posible_lista + (comprobar_posicion_anchura(tablero,i[0])[0:])
        #ponemos a 1 la posicion en la que nos encontramos del for
        tablero[i[0][0]][i[0][1]]=1
        #comprobamos que no se haya llegado a la solucion
        if (np.count_nonzero(tablero)==size_tablero**2):
            lista_soluciones.append(array_solucion)
            return 1
        # si ese hijo no esta, pone su posicion del tablero a 0
        tablero[i[0][0]][i[0][1]]=0
    #guardamos la posicion del recorrido del arbol en un array
    array_solucion.append(ficha_posicion)
    #ponemos a 1 dicha posicion
    tablero[array_solucion[len(array_solucion)-1][0]][array_solucion[len(array_solucion)-1][1]]=1
    #volvemos a comprobar que el tablero no se haya completado
    if (np.count_nonzero(tablero)==size_tablero**2):
        #si se ha llenado de 1, se añade la solcion
        lista_soluciones.append(array_solucion)
        return 1
    aux_count = 0
    #recorremos los posibles hijos candidatos
    for i in array_posible_hijos:
        aux_count += 1    
        # si el padre del hijo, es el mismo que la posicion en la que nos encontramos, significa que debemmos seguir buscando por ahi
        if i[1]==ficha_posicion:
            #ficha_posicion=i[0]
            # llamamos de nuevo a la funcion recursiva con la nueva posicion en la que nos encontramos
            resultado=seleccion_anchura(tablero,i[0],array_posible_lista)
            # si resultado es distinto de 0, significa que ha encontrado una solucion y debe salirse recursivamente hacia atras.
            if resultado!=0:
                return resultado
    # si una vez recorrido el for de hijos, y ninguno de los padres de ellos se corresponde con la posicion actual, ponemos la posicion en la que nos encontramos a 0 y quitamos de la lista 
    # de soluciones la ultima que se añadió
    tablero[array_solucion[len(array_solucion)-1][0]][array_solucion[len(array_solucion)-1][1]]=0
    array_solucion.pop()
    #devolvemos 0, lo que nos hará irnos hacia el for de la recursividad anterior y seguir explorando los hijos que quedan.
    return 0

# Declaracion de variables e inicio del juego

In [10]:
intro=0
size_tablero= 0
# elejimos el tamaño del tablero y comprobamos que se haya introducido bien
while intro == 0:
    print("Elija el tamaño del tablero:")
    size_tablero=input()
    if size_tablero.isnumeric():
        intro=1
        size_tablero= int(size_tablero)
    else:
        print("Valor no válido")

tablero = np.zeros((size_tablero, size_tablero))

Elija el tamaño del tablero:
Valor no válido
Elija el tamaño del tablero:


In [11]:
#declaramos todas la variables necesarias para la ejecucion
# ficha_posicion_r=(random.randint(0,size_tablero-1),random.randint(0,size_tablero-1))
ficha_posicion_r=(0,0)
num_paso=1
tablero[ficha_posicion_r[0]][ficha_posicion_r[1]]=num_paso
lista_soluciones = []
print(tablero)
juego=0
array_posible_real=[]
array_solucion=[]
array_posible_real.insert(0,[ficha_posicion_r,(-1,-1)])

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Implementación en anchura


In [12]:
#implementamos una llamada al tiempo que tarda en hacerse y se invoca a la funcion recursiva con los valores iniciales
inicio =  time.time()
seleccion_anchura(tablero,ficha_posicion_r,array_posible_real)
fin = time.time()

In [13]:
#termina el juego y pintamos las soluciones
print("Juego terminado")
if len(lista_soluciones) == 0:
    print("No tiene solucion")
else:
    for i in lista_soluciones:
        pintar_camino(tablero, i)
        print(i)
        print("Tiempo:",fin-inicio)

        print("Tablero:\n",tablero)

Juego terminado
[(0, 0), (1, 2), (2, 0), (0, 1), (1, 3), (3, 4), (2, 2), (4, 1), (3, 3), (1, 4), (0, 2), (1, 0), (3, 1), (4, 3), (2, 4), (0, 3), (1, 1), (3, 0), (4, 2), (2, 1), (4, 0), (3, 2), (4, 4), (2, 3), (0, 4)]
Tiempo: 0.503532886505127
Tablero:
 [[ 1.  4. 11. 16. 25.]
 [12. 17.  2.  5. 10.]
 [ 3. 20.  7. 24. 15.]
 [18. 13. 22.  9.  6.]
 [21.  8. 19. 14. 23.]]
