In [6]:
import numpy
import random
import time

# Definicion de funciones

In [7]:
# busqueda de la posicion del caballo mediante el número en el que se encuetra y el tablero
def get_coord(number, matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == number:
                return i, j

# funcion que devuelve si se puede o no mover el caballo a la posición deseada
def get_move(val_pos, n, chessboard):
    if (val_pos[0] >= 0) and (val_pos[0] < n) and (val_pos[1] >= 0) and (val_pos[1] < n) and (chessboard[val_pos[0], val_pos[1]] == 0):
        return True # Se devuelve True si el movimiento se encuentra dentro del tablero y no se encuentra ocupado
    return False

# funcion que devuelve el numero de movimientos posibles para el caballo
def get_moves_number(val_pos, n, chessboard):
    moves = 0
    if get_move((val_pos[0] + 2, val_pos[1] + 1), n, chessboard):
        moves += 1
    if get_move((val_pos[0] + 2, val_pos[1] - 1), n, chessboard):
        moves += 1
    if get_move((val_pos[0] - 2, val_pos[1] + 1), n, chessboard):
        moves += 1
    if get_move((val_pos[0] - 2, val_pos[1] - 1), n, chessboard):
        moves += 1
    if get_move((val_pos[0] + 1, val_pos[1] + 2), n, chessboard):
        moves += 1
    if get_move((val_pos[0] + 1, val_pos[1] - 2), n, chessboard):
        moves += 1
    if get_move((val_pos[0] - 1, val_pos[1] + 2), n, chessboard):
        moves += 1
    if get_move((val_pos[0] - 1, val_pos[1] - 2), n, chessboard):
        moves += 1
    return moves

#funcion para ordenar los movimientos de menor a mayor
def bubble_sort(lista):
    for i in range(len(lista)-1,0,-1):
        for j in range(i):
            if lista[j][0]>lista[j+1][0]:
                aux=lista[j]
                lista[j]=lista[j+1]
                lista[j+1]=aux
    return lista


In [8]:
# funcion recursiva para la busqueda de la solucion
def knights_tour(posicion,n,move_number,chessboard):
    # generamos una copia de la variable global por cada llamada recursiva
    global movements_order
    movements_order = []
    # si el numero de movimientos es igual al numero de casillas del tablero, se ha llegado al final
    if move_number>n*n:
        #adjuntamos la solucion al array de movimientos
        different_solutions.append(chessboard.copy())
        print(f"\rnumero de soluciones encontradas = {len(different_solutions)}", end="")
        # descomentar esto si queremos mas de una solucion
        # x,y = get_coord(move_number-1, chessboard)
        # chessboard[x,y] = 0
        return True
    # obtenemos el numero de hijos que tendran los diferentes nodos
    for i in movements:
        x,y = get_coord(move_number-1, chessboard)
        posicion=(x+i[0],y+i[1])
        if get_move(posicion,n,chessboard):
            num_valores_aux=get_moves_number(posicion,n,chessboard)
            movements_order.append((num_valores_aux,posicion))

    # ordenamos los movimientos de menor a mayor segun el numero de hijos
    movements_order= bubble_sort(movements_order)
    # recorremos los movimientos de menor a mayor
    for i in movements_order:
        #actualizamos el tablero
        chessboard[i[1][0],i[1][1]] = move_number
        # llamamos recursivamente a la funcion con la posicion actualizada
        x=knights_tour(i[1],n,move_number+1,chessboard)
        # comentar este if si queremos más de 1 solucion
        if(x==True):
            return True
        
    
    # actualizamos el tablero        
    x,y = get_coord(move_number-1, chessboard)
    chessboard[x,y] = 0
    return False
            

In [13]:
# generamos el main del programa y elegimos el tablero
def main():
    intro=0
    move_number=1
    while intro == 0:
        size_tablero=input("Elija el tamaño del tablero:")
        # Control de errores
        if size_tablero.isnumeric():
            intro=1
            size_tablero= int(size_tablero)
        else:
            print("Valor no válido")
        posicion=input("Elija la posición inicial del caballo con la forma x,y:")
        # Control de errores
        posicion=posicion.split(",")
        try:
            posicion=(int(posicion[0]),int(posicion[1]))
            posicion= (posicion[0],posicion[1])
            intro=1
        except:
            print("Valor no válido")
            intro=0

    chessboard = numpy.zeros((size_tablero, size_tablero))
    chessboard[posicion[0],posicion[1]] = move_number
    move_number+=1
    inicio = time.time()
    # llamamos a la funcion recursiva
    knights_tour(posicion,size_tablero,move_number,chessboard)
    fin = time.time()
    # mostramos el numero de soluciones encontradas y imprimimos el tiempo de ejecucion y tablero
    if len(different_solutions)>=1:
        for i,j in enumerate(different_solutions):
            print(f"\nnum sol = {i}")
            print(j)
        print(f"Tiempo de ejecución: {fin-inicio}")

In [14]:
different_solutions=[]
movements=[(1,2),(2,1),(2,-1),(1,-2),(-1,-2),(-2,-1),(-2,1),(-1,2)]
movements_order=[]
main()

numero de soluciones encontradas = 1
num sol = 0
[[ 1. 12. 25. 18.  3.]
 [22. 17.  2. 13. 24.]
 [11.  8. 23.  4. 19.]
 [16. 21.  6.  9. 14.]
 [ 7. 10. 15. 20.  5.]]
Tiempo de ejecución: 0.001033782958984375
